"""Insert authors

Revision ID: 0182dd89602f
Revises: 075871b5258d
Create Date: 2025-02-22 17:07:56.702344

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0182dd89602f"
down_revision: Union[str, None] = "075871b5258d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO authors (first_name, last_name, birth_date, nationality, created_at, updated_at)
        VALUES
            ('John', 'Doe', '1980-05-15', 'USA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('Jane', 'Smith', '1975-08-22', 'CAN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('Albert', 'Einstein', '1879-03-14', 'GER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('Marie', 'Curie', '1867-11-07', 'POL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('Isaac', 'Newton', '1642-01-04', 'ENG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    """)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM authors WHERE first_name IN ('John', 'Jane', 'Albert', 'Marie', 'Isaac');
    """)
