environment: "{{env.get('PROGRAM_ENVIRONMENT', 'dev')}}"
app_name: "{{env.get('APP_NAME', 'Descartes')}}"

fastapi:
  debug: {{env.get('FASTAPI_VERBOSE', False) | string | upper == "TRUE"}}

logging:
  version: 1
  disable_existing_loggers: false
  loggers:    
    sql:
      level: INFO
      propagate: true
    app:
      level: INFO
      propagate: true
    uvicorn:
      handlers: ["{{env.get('APP_LOG_FORMAT', 'docker')}}"]
      level: INFO
      propagate: false
    uvicorn.error:
      handlers: ["{{env.get('APP_LOG_FORMAT', 'docker')}}"]
      level: INFO
      propagate: false
    uvicorn.access:
      handlers: ["{{env.get('APP_LOG_FORMAT', 'docker')}}"]
      level: INFO
      propagate: false
    
  root:
    level: INFO
    handlers: ["{{env.get('APP_LOG_FORMAT', 'docker')}}"]
  handlers:
    docker:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: dockerjson
      level: INFO
    apache:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: apache
      level: INFO
  formatters:
    dockerjson:
      '()': src.helper.logging.DockerJsonFormatter
    apache:
      '()': src.helper.logging.ApacheFormatter